apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dyndns.fullname" . }}-cm
data:
  config.yml: |
    {{- if .Values.cloudflare.enabled }}
    cloudflare:
      email: {{ .Values.cloudflare.email }}
      apiKeyPath: {{ .Values.cloudflare.apiKeyPath }}
    {{- end }}

    {{- if .Values.namecheap.enabled }}
    namecheap:
      user: {{ .Values.namecheap.email }}
      apiKeyPath: {{ .Values.namecheap.apiKeyPath }}
    {{- end }}

    domain: {{ .Values.domain }}
    records:
      {{- toYaml .Values.records | nindent 6 }}
      
    fritzbox:
      address: {{ .Values.fritzbox.address }}
      interval: {{ .Values.fritzbox.interval }}
      timeout: {{ .Values.fritzbox.timeout }}

    ipv6:
      {{- toYaml .Values.ipv6 | nindent 6 }}